#q6.py
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("student_performance.csv")
plt.bar(df['Student'],df['Final_Score'])
plt.xlabel('Student names')
plt.ylabel('Final score')
plt.title('Bar graph of student names vs final score')
plt.savefig('final_scores.png')
plt.show()
plt.scatter(df['Hours_Studied'],df['Final_Score'])
plt.xlabel('Hours studied')
plt.ylabel('Final score')
plt.title('Scatter plot of hours studied vs final score')
plt.savefig('study_vs_scores.png')
plt.show()
plt.hist(df['Final_Score'])
plt.xlabel('Final score')
plt.ylabel('Frequency')
plt.title('Histogram of final scores')
plt.savefig('score_distribution.png')
plt.show()
plt.scatter(df["Attendance"],df["Final_Score"])
plt.xlabel('Attendance')
plt.ylabel('Final score')
plt.title('Scatter plot of attendance vs final score')
plt.savefig('custom_plot.png')
plt.show()